image: registry.gitlab.com/pages/hugo/hugo_extended:latest

pages:
  script:
    - git submodule update --init --recursive  # 拉取子模块
    - hugo  --minify --baseURL "http://blog.xueyao.tech/"
  artifacts:
    paths:
      - public  # Hugo 生成的静态文件放在 `public` 文件夹中
  only:
    - main  # 只在 main 分支上部署
