### Site info:
title: 薛尧技术博客
tagline: 专注PHP的小白
author: 薛尧
email: yaoxue2014@hotmail.com
description: "薛尧博客." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "薛尧, 薛尧博客, php技术"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xueyao.org" # the base hostname & protocol for your site
locale: en_US
#locale: cn

### Personal info and site tools info:
twitter_username: flowstone
github_username:  flowstone
disqus_shortname: flowstone
favicon:     "/images/favicon.ico"
aboutme: 您好，欢迎来到我的博客，我叫薛尧，网名流体石头，技术宅，热爱编程。 # these are shown on aboutme-sidebar.
aboutme_photo: https://avatars3.githubusercontent.com/u/6500681?v=3&u=8b21049902d0e50df9d474899a98116a07fd9f74&s=140 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "友情链接"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    #- name: Freshman21
     # href: http://yulijia.net/freshman21
      #title: Another Jekyll blog theme
    - name: github
      href: http://github.com
      title: github


### Build settings
markdown: kramdown
# highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 1
