# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 薛尧博客
email: xueyao2014@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  All about Spaghetti-san Project
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xueyao.me" # the base hostname & protocol for your site
twitter_username:  
github_username:  flowstone
facebook_username:   
disqus_id: flowstones.disqus.com

# Gems
gems: 
- jekyll-archives
- jekyll-paginate

# Config
paginate: 5
paginate_path: "page/:num"
# Build settings
markdown: kramdown

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
