# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 薛尧博客
email: yaoxue2014@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  专注PHP的小白.
baseurl: "" # the subpath of your site, e.g. /blog
permalink : '/:year/:title.html'
url: "http://xueyao.me" # the base hostname & protocol for your site
twitter:
  username: #twitter username here
facebook:
  app_id: 1234
  publisher: 1234
google_plus: #gplus id or username

# Optional settings
github: http://github.com/flowstone
linkedin: #linkedin username
disqus_username: #Your disqus_username to add comments on the post
google_analytics: #your GA unique id (UA-xxxxxxxx-x)

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
paginate: 5
paginate_path: 'p/:num'
