name: Sync to SFTP

on:
  push:
    branches:
      - main  # 可以根据需要修改为你想要监听的分支
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: domain-pages  # 替换为你要检出的具体分支名
            
      - name: Deploy with Password
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SF_SFTP_USER }}
          server: ${{ secrets.SF_SFTP_HOST }}
          port: ${{ secrets.SF_SFTP_PORT }}
          local_path: './*'
          remote_path: ${{ secrets.SF_SFTP_TARGET_DIR }}
          sftp_only: true
          password: ${{ secrets.SF_SFTP_PASSWORD }}
          
