name: Sync Articles

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout blog repository
      - name: Checkout blog repo
        uses: actions/checkout@v2

      # Checkout articles repository as a submodule
      - name: Checkout articles repo
        uses: actions/checkout@v2
        with:
          repository: flowstone/blog-articles
          path: content/post
          token: ${{ secrets.GITHUB_TOKEN }}

      

      # If there are changes, commit and push them to the blog repo
      - name: Commit and push articles changes
        run: |
          git add content/post
          git commit -m "Sync articles from new repository"
          git push origin main
